### ISSUE TITLE
Disponibilizar a base reconciliada em formato RDF

### ISSUE THREAD

**Issue by lubianat** [jvfe/wikidata_panglaodb#1]
Após a reconciliação com o Wikdiata, representar a base em formato RDF e disponibilizar. 

Não conheço as boas práticas para fazer isso, mas dá pra fazer.

**Comment by jvfe** [comment]
Acredito que 6d6ee36 e a integração posterior dos dados na Wikidata fecha esse issue, mas pode re-abrir caso seja necessário.
